# Catppuccin Macchiato Theme for Yazi

[fg]
default = "#cad3f5"
black = "#181825"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"
bright_black = "#6e738d"
bright_red = "#ed8796"
bright_green = "#a6da95"
bright_yellow = "#eed49f"
bright_blue = "#8aadf4"
bright_magenta = "#f5bde6"
bright_cyan = "#8bd5ca"
bright_white = "#cad3f5"

[bg]
default = "#24273a"
black = "#24273a"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"
bright_black = "#24273a"
bright_red = "#ed8796"
bright_green = "#a6da95"
bright_yellow = "#eed49f"
bright_blue = "#8aadf4"
bright_magenta = "#f5bde6"
bright_cyan = "#8bd5ca"
bright_white = "#cad3f5"

[ui]
fg = "#cad3f5"
bg = "#24273a"
border = "#6e738d"
title = "#8aadf4"
preview = "#cad3f5"
highlighted = "#f5bde6"
bar_border = "#8aadf4"
bar_fg = "#cad3f5"
bar_bg = "#313244"
