$mainMod = SUPER

# --- APPS ---
bind = $mainMod, T, exec, kitty
bind = $mainMod, E, exec, thunar 
bind = $mainMod, A, exec, wofi --show drun
bind = $mainMod, G, exec, firefox
bind = $mainMod, c, exec, telegram-desktop

# --- SYSTEM ---
bind = $mainMod, Q, killactive
bind = $mainMod CTRL, Q, exec, swaylock
bind = $mainMod CTRL, L, exit
bind = $mainMod, M, exec, wlogout --protocol layer-shell

bind = $mainMod, Return, fullscreen

# --- WINDOWS ---
bind = $mainMod, W, togglefloating
bind = $mainMod, B, pseudo

# --- SCREENSHOT ---
bind = $mainMod, P, exec, hyprshot -m region --clipboard


bind = $mainMod CTRL, right, workspace, +1
bind = $mainMod CTRL, left, workspace, -1
bind = $mainMod ALT, right, movetoworkspace, +1
bind = $mainMod ALT, left, movetoworkspace, -1

# --- RESIZE ---
bind = $mainMod CTRL, l, resizeactive, 10 0
bind = $mainMod CTRL, h, resizeactive, -10 0
bind = $mainMod CTRL, k, resizeactive, 0 -10
bind = $mainMod CTRL, j, resizeactive, 0 10

# --- MOUSE ---
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
