$mainMod = SUPER

# --- APPS ---
bind = $mainMod, T, exec, kitty
bind = $mainMod, E, exec, kitty --class yazi -e yazi 
bind = $mainMod, A, exec, rofi -show drun
bind = $mainMod, G, exec, firefox
bind = $mainMod, c, exec, telegram-desktop

# --- SYSTEM ---
bind = $mainMod, Q, killactive
bind = $mainMod CTRL, L, exec, sleep 1 && hyprlock
bind = $mainMod, L, exit
bind = $mainMod, M, exec, wlogout --protocol layer-shell

bind = $mainMod, Return, fullscreen

# --- WINDOWS ---
bind = $mainMod, W, togglefloating
bind = $mainMod, B, pseudo

# --- SCREENSHOT ---
bind = $mainMod, P, exec, hyprshot -m region --clipboard


bind = $mainMod CTRL, right, workspace, +1
bind = $mainMod CTRL, left, workspace, -1
bind = $mainMod ALT, right, movetoworkspace, +1
bind = $mainMod ALT, left, movetoworkspace, -1

# --- RESIZE ---
bind = $mainMod CTRL, l, resizeactive, 10 0
bind = $mainMod CTRL, h, resizeactive, -10 0
bind = $mainMod CTRL, k, resizeactive, 0 -10
bind = $mainMod CTRL, j, resizeactive, 0 10

# --- MOUSE ---
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# --- AUDIO & VOLUME ---
bindel = , XF86AudioMute, exec, pamixer -t
bindel = , XF86AudioLowerVolume, exec, pamixer -d 5
bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = , XF86AudioMicMute, exec, pamixer --default-source -t

# --- BRIGHTNESS ---
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+

# --- POWER PROFILES ---
bind = , XF86Launch5, exec, powerprofilesctl cycle