windowrulev2 = float, class:^(file_progress)$
windowrulev2 = float, class:^(confirm)$
windowrulev2 = float, class:^(dialog)$
windowrulev2 = float, class:^(download)$
windowrulev2 = float, class:^(notification)$
windowrulev2 = float, class:^(error)$
windowrulev2 = float, class:^(splash)$
windowrulev2 = float, class:^(confirmreset)$

windowrulev2 = float, title:^(Open File)$
windowrulev2 = float, title:^(branchdialog)$
windowrulev2 = float, class:^(viewnior)$

windowrulev2 = float, class:^(pavucontrol-qt)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(file-roller)$

windowrulev2 = fullscreen, class:^(wlogout)$
windowrulev2 = float, title:^(wlogout)$

windowrulev2 = idleinhibit, class:^(mpv)$
windowrulev2 = float, title:^(Media viewer)$

windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$

windowrulev2 = float, class:^(vesktop)$, title:^(Discord Popout)$
windowrulev2 = pin, class:^(vesktop)$, title:^(Discord Popout)$