windowrule = float 1 class:^(file_progress)$
windowrule = float 1 class:^(confirm)$
windowrule = float 1 class:^(dialog)$
windowrule = float 1 class:^(download)$
windowrule = float 1 class:^(notification)$
windowrule = float 1 class:^(error)$
windowrule = float 1 class:^(splash)$
windowrule = float 1 class:^(confirmreset)$
windowrule = float 1 title:^(Open File)$
windowrule = float 1 title:^(branchdialog)$
windowrule = float 1 class:^(viewnior)$
#windowrule = float 1 class:^(pavucontrol-qt)$
#windowrule = float 1 class:^(pavucontrol)$
windowrule = float 1 class:^(file-roller)$
windowrule = fullscreen 1 class:^(wlogout)$
windowrule = float 1 title:^(wlogout)$
windowrule = float 1 title:^(Media viewer)$
windowrule = float 1 title:^(Picture-in-Picture)$
windowrule = pin 1 title:^(Picture-in-Picture)$
windowrule = float 1 class:^(vesktop)$ title:^(Discord Popout)$
windowrule = pin 1 class:^(vesktop)$ title:^(Discord Popout)$