windowrule = float 1, match:class file_progress
windowrule = float 1, match:class confirm
windowrule = float 1, match:class dialog
windowrule = float 1, match:class download
windowrule = float 1, match:class notification
windowrule = float 1, match:class error
windowrule = float 1, match:class splash
windowrule = float 1, match:class confirmreset
windowrule = float 1, match:title Open File
windowrule = float 1, match:title branchdialog
windowrule = float 1, match:class ^$
windowrule = float 1, match:class file-roller
windowrule = fullscreen 1, match:class wlogout
windowrule = float 1, match:title wlogout
windowrule = float 1, match:title Media viewer
windowrule = float 1, match:title Picture-in-Picture
windowrule = pin 1, match:title Picture-in-Picture
windowrule = float 1, match:class vesktop, match:title Discord Popout
windowrule = pin 1, match:class vesktop, match:title Discord Popout
windowrule = opacity 0.9 override 0.9 override, match:title btop
windowrule = float 1, match:title exegol-history
windowrule = size 900 450, match:title exegol-history
windowrule = center 1, match:title exegol-history