# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-56a87178-0660-4d42-8eb6-db2f888ae85f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-56a87178-0660-4d42-8eb6-db2f888ae85f".device = "/dev/disk/by-uuid/56a87178-0660-4d42-8eb6-db2f888ae85f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7795-A3C0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f57813ed-981c-4a24-9766-3d78f675b917"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}